### ISSUE TITLE
where are the original json files?

### ISSUE THREAD

**Issue by tausi0661** [AlexisEvo/d2r-loot-filter#1]
thanks a lot for your help and i think i can run it successfully by packing the mod into a .mpq file. but can i get a copy of the original json files? I tried the cascview tool but it didn't work :( not sure if it is due to the disk space or something else...

i just want to compare the original files with your ones and see if i can change something by myself. thank u again~~

**Comment by AlexisEvo** [comment]
They're in the [initial commit](https://github.com/AlexisEvo/d2r-loot-filter/commit/68d82c178f99aeda724e39d4c6f13fc33cf9c6b9). If you're going to be modding the game, you need to get cascview working.
