### ISSUE TITLE
List of all changes

### ISSUE THREAD

**Issue by GorOps** [AlexisEvo/d2r-loot-filter#3]
It would be nice if you could add what all this filter will change. I looked through some of the commits and was able to pick these out:

- Adds big box for Lem and higher runes
- Hides keys
- Hides Chipped, Flawed, Regular gems. Adds color to Flawless and Perfect gems.
- Hides Strangling Gas Potion, Fulminating Potion, Choking Gas Potion, Exploding Potion, Rancid Gas Potion, Oil Potion, Stamina Potion, Antidote Potion, Thawing Potion, 
- Adds number to health and mana potions and shortens name
- Highlights Small and Grand charms
- Hides Arrows, Bolts
- Changes color of Scrolls of ID/TP and Tomes of ID/TP
- Changes color of small and full rejuv
- Adds sound effects for certain item drops (jewels, runes, charms, superior??)
- Low Quality / Cracked / Crude / Damaged items are black to attempt to blend in with the item box. _Why not hide them???_
- Big box for diablo/baal essence

**Comment by clint-chu** [comment]
> Can you please add a justification as to why changes are required to /global/excel vs changes required to local/lang/strings? Much appreciated (would help someone first looking at this understand the structure better)!

I'm curious of this as well.

**Comment by AlexisEvo** [comment]
- Not gonna put a detailed list of changes, look at commit history, this is honestly meant to be a super opinionated filter that suits my own needs
- lang/strings json edits are entirely tied to the names/colors of items that dropped. stuff in excel dir is more complicated, like changing the drop sound, changing volume of drop sound, etc.
- it gets more complicated when you look into the new engine rendering techniques, for the most part anything in the excel folders is either intended for legacy graphics or are base engine mechanics carried over to d2r, but the entire hd folder is new and is what enables stuff like drop beams https://github.com/AlexisEvo/d2r-loot-filter/commit/9d8f4db84125b0bfc05472487adb70ad0efc2d44
