### ISSUE TITLE
Bans

### ISSUE THREAD

**Issue by Nukehide** [AlexisEvo/d2r-loot-filter#4]
You guys are worried about bans, yet you are making huge pick boxes - such things clearly break core game rules and most likely won't be left unnoticed. Pretty much same to me as if it was breakpoint hack.

It would be much more reliable and safer if it was a simple color lootfilter.

**Comment by AlexisEvo** [comment]
I'm not worried about bans, I've been banned from Diablo 2 more times than I can count. I also think it's highly unlikely Blizzard would resort to such levels. 

If Blizzard/VV is actually against the existence of this mod and they contact me I will pull it and stop development. My email is unchanged from the last several times they've reached out. Until then, this isn't the correct medium for you to vent your moral high ground.
