### ISSUE TITLE
Missing String  Missing String

### ISSUE THREAD

**Issue by Quadrat1c** [AlexisEvo/d2r-loot-filter#5]
Edit:
If you are getting Missing String's see barrettj's reply.

**Comment by Quadrat1c** [comment]
> 
> 
> Incorrect. They implemented a queue system and you are in the login queue. The loot filter just doesn't have the localized strings explaining as such yet. If you wait patiently you'll get in, you just don't have an (almost useless) ETA in the form of a queue position that updates irregularly.

That explains it! Thank you

**Comment by AlexisEvo** [comment]
This isn't a file that's managed by the mod, what happened is Blizzard added a new file but your -direct -txt install doesn't have it. Either re-extract the data from cascview and reinstall the mod, or download the MPQ from discord which doesn't have this issue.
