### ISSUE TITLE
invalid discord invite link

### ISSUE THREAD

**Issue by Larsy93** [AlexisEvo/d2r-loot-filter#6]
invalid discord invite link

**Comment by AlexisEvo** [comment]
Friends of mine have received Discord permabans for developing (actual) D2R cheats. I don't think this is a cheat, Blizzard apparently does not think this is a cheat (or they'd take the bare minimum actions to stop it, like emailing me as my readme.md suggests), but I don't expect some minimum wage discord customer support employee to understand that. People are still going to report me anyway as they think it's """unfair""". It's my personal discord so I've unlinked it from this project.
